version: "3.7"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  blog-service:
    build:
      context: ./blog-service
    ports:
      - "5002:5002"
    depends_on:
      - db
  comment-service:
    build:
      context: ./comment-service
    ports:
      - "5003:5003"
    depends_on:
      - db
  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    depends_on:
      - db

volumes:
  postgres_data:
 
